// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace OutlookSpamDetectionML.Model
{
    public class ModelInput
    {
        [ColumnName("spam"), LoadColumn(0)]
        public bool Spam { get; set; }


        [ColumnName("message"), LoadColumn(1)]
        public string Message { get; set; }


    }
}
